### ISSUE TITLE
Is flag `-type-in-type` required for this repository?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/SetHITs#3] opened 2022-03-07 09:12 UTC
Until now, this flag has not been required, but starting with https://github.com/UniMath/UniMath/pull/1467, this might be necessary. I am not sure which change exactly triggers the build error:
```
Cloning into 'SetHITs'...
~/work/UniMath/UniMath/SetHITs ~/work/UniMath/UniMath
COQDEP VFILES
COQC prelude/imports.v
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ + _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ - _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ * _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ = _" was already used in scope type_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ <-> _" was already used in scope type_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ > _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ < _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ <= _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 2, characters 0-39:
Warning: Notation "_ >= _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 3, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 3, characters 0-43:
Warning: Notation "_ <-> _" was already used in scope type_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 3, characters 0-43:
Warning: Notation "_ = _" was already used in scope type_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 3, characters 0-43:
Warning: Notation "_ = _" was already used in scope type_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 3, characters 0-43:
Warning: Notation "_ <-> _" was already used in scope type_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 3, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing]
File "./prelude/imports.v", line 12, characters 0-57:
Error: Universe inconsistency. Cannot enforce UU.u0 = Set because Set
< UU.u0.

make[1]: *** [Makefile:716: prelude/imports.vo] Error 1
make: *** [Makefile:339: all] Error 2
Error: Process completed with exit code 2.
```
(Complete CI run at https://github.com/UniMath/UniMath/runs/5442353189?check_suite_focus=true.)

**Comment by m-lindgren** [comment] 2022-11-06 22:25
The problem is that the PR calls  `bool_rec : ∏ (P : bool → Set), P true → P false → ∏ b : bool, P b` and `coprod_rec`, which also use the Set-eliminator. I suggested some changes to the PR that I tried successfully compiling SetHIT with, so no need `-type-in-type`.

**Comment by m-lindgren** [comment] 2022-11-07 07:54
So I was wrong, `-type-in-type` is currently needed, but for a completely different reason: 
```
        coqc SetHITs/code/examples/groups.{glob,vo} (exit 1)
File "./SetHITs/code/examples/groups.v", line 118, characters 12-20:
Error:
The term "group_ax" has type "UU" while it is expected to have type
"Type" (universe inconsistency: Cannot enforce UU.u0 <=
hit_signature.u0 because hit_signature.u0 < UU.u0).

        coqc SetHITs/code/examples/rings.{glob,vo} (exit 1)
File "./SetHITs/code/examples/rings.v", line 192, characters 12-19:
Error:
The term "ring_ax" has type "UU" while it is expected to have type
"Type" (universe inconsistency: Cannot enforce UU.u0 <=
hit_signature.u0 because hit_signature.u0 < UU.u0).

...
```
I believe these comes from this [recent commit](https://github.com/UniMath/SetHITs/commit/12cd45e6676893cafb1abe823495a7c8c3bac11a) with innocent looking changes like:
```diff
  (** Labels of group axioms *)
-Inductive group_ax :=
+Inductive group_ax : UU :=
 | assoc : group_ax
```
I assume this is because UniMath has `Definition UU := Type.` instead of having `UU` be a Notation (or just using Type).

**Comment by m-lindgren** [comment] 2023-03-12 11:05
Closing this following #14. `-type-in-type` is not needed for this repository. The original issue was that the PR UniMath/UniMath#1467 inadvertently used `Set`-valued eliminators which caused a universe inconsistency when building this satellite.

**Closed by m-lindgren** 2023-03-12 11:05 UTC
